export default defineNuxtConfig({
  devtools: { enabled: false },
  css: [
    "./assets/scss/main.scss",
    "primevue/resources/primevue.min.css",
    "primeicons/primeicons.css",
    "@fortawesome/fontawesome-svg-core/styles.css",
  ],
  app: {
    baseURL: "/Portfolio/",
  },
  modules: [
    "nuxt-primevue",
    "nuxt-swiper",
    "@hypernym/nuxt-anime",
    "@nuxtjs/tailwindcss",
    "@pinia/nuxt",
    "nuxt-swiper",
  ],
  swiper: {
    // Swiper options
    //----------------------
    // prefix: 'Swiper',
    // styleLang: 'css',
    // modules: ['navigation', 'pagination'], // all modules are imported by default
  },
  plugins: ["~/plugins/lightbox.ts", "~/plugins/fontawesome.js"],
  primevue: {
    usePrimeVue: true,
    cssLayerOrder: "tailwind-base, primevue, tailwind-utilities",
    components: {
      include: [
        "PrimeVue",
        "Button",
        "DataTable",
        "Column",
        "Toast",
        "Menubar",
        "MegaMenu",
        "ProgressSpinner",
        "InputSwitch",
        "SpeedDial",
        "InputText",
        "InputNumber",
        "ScrollTop",
        "InputMask",
        "MultiSelect",
        "Slider",
        "Dialog",
        "Dropdown",
        "Checkbox",
        "RadioButton",
        "Textarea",
        "Calendar",
        "ProgressBar",
        "chip",
        "Chips",
        "Accordion",
        "AccordionTab",
        "Menubar",
        "Message",
        "FileUpload",
        "ToggleButton",
        "TabView",
        "TabPanel",
        "Tree",
        "Tooltip",
        "Paginator",
        "Rating",
        "Sidebar",
        "SplitButton",
        "Toast",
        "TreeTable",
        "ConfirmDialog",
        "Menu",
        "OverlayPanel",
        "Panel",
        "PickList",
        "OrderList",
        "Schedule",
        "DataScroller",
        "Timeline",
        "OrganizationChart",
        "Galleria",
        "Tag",
        "Badge",
        "TriStateCheckbox",
        "Card",
        "Avatar",
        "Image",
      ],
    },
    options: {
      ripple: true,
    },
  },
});
